name: Publish to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1

      - name: Build docs
        run: npm ci && npm run docs:build

      - name: Deploy to gh-pages
        uses: s0/git-publish-subdir-action@v2.4.0
        env:
            REPO: self
            BRANCH: gh-pages
            FOLDER: docs
            GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
